# Generated by Django 4.2.11 on 2026-03-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=120)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rescheduled', 'Rescheduled'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('response_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
