# Generated by Django 4.2.28 on 2026-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
