import base64
import json
import time
import requests
import logging
from django.conf import settings

logger = logging.getLogger(__name__)


def _build_email_connection():
    # Keep SMTP failures bounded so web workers do not hang.
    from django.core.mail import get_connection
    return get_connection(timeout=getattr(settings, 'EMAIL_TIMEOUT', 8))


def _get_vapid_public_key():
    """Get the VAPID public key for the frontend to use."""
    return getattr(settings, 'VAPID_PUBLIC_KEY', None)


def send_appointment_email(staff_email, visitor_name, appointment_date, message):
    from django.core.mail import send_mail
    
    if not staff_email:
        logger.warning('send_appointment_email skipped: no staff_email provided')
        return

    subject = 'New Appointment Request'
    body = (
        f'Visitor Name: {visitor_name}\n'
        f'Date: {appointment_date}\n'
        f'Message: {message or "No message provided."}\n'
    )

    try:
        send_mail(
            subject,
            body,
            settings.DEFAULT_FROM_EMAIL,
            [staff_email],
            fail_silently=False,
            connection=_build_email_connection(),
        )
        logger.info(f'Appointment email sent successfully to {staff_email}')
    except Exception as e:
        logger.error(f'Failed to send email to {staff_email}: {str(e)}')
        raise


def send_appointment_response_email(visitor_email, visitor_name, status, response_note, appointment_date, staff_name):
    from django.core.mail import send_mail
    
    if not visitor_email:
        return

    subject = f'Update on Your Appointment Request ({status})'
    body = (
        f'Hello {visitor_name},\n\n'
        f'Your appointment request has been updated to: {status}\n'
        f'Date: {appointment_date}\n'
        f'Staff: {staff_name}\n\n'
        f'Staff response:\n{response_note}\n\n'
        'Thank you.'
    )
    send_mail(
        subject,
        body,
        settings.DEFAULT_FROM_EMAIL,
        [visitor_email],
        fail_silently=True,
        connection=_build_email_connection(),
    )


def _urlsafe_b64encode(data):
    """Encode bytes to URL-safe base64 without padding."""
    if isinstance(data, str):
        data = data.encode('utf-8')
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('utf-8')


def _create_vapid_jwt():
    """Create a VAPID JWT for Web Push authentication."""
    vapid_public_key = getattr(settings, 'VAPID_PUBLIC_KEY', None)
    vapid_private_key = getattr(settings, 'VAPID_PRIVATE_KEY', None)
    vapid_subject = getattr(settings, 'VAPID_SUBJECT', 'mailto:admin@example.com')
    
    if not vapid_public_key or not vapid_private_key:
        return None, None
    
    # JWT header
    header = {
        'typ': 'JWT',
        'alg': 'ES256',
    }
    
    # JWT payload
    payload = {
        'aud': 'https://fcm.googleapis.com',
        'exp': int(time.time()) + 3600,  # 1 hour expiry
        'sub': vapid_subject,
    }
    
    # For ES256, we need to sign the header.payload with the private key
    # Using a simplified approach with the crypto library
    try:
        import ecdsa
        from ecdsa import NIST256p
        
        # Create signing key from private key
        private_key_bytes = _urlsafe_b64decode(vapid_private_key)
        signing_key = ecdsa.SigningKey.from_pem(private_key_bytes)
        
        # Encode header and payload
        header_b64 = _urlsafe_b64encode(json.dumps(header))
        payload_b64 = _urlsafe_b64encode(json.dumps(payload))
        
        # Create signature
        message = f"{header_b64}.{payload_b64}".encode('utf-8')
        signature = signing_key.sign(message, hashfunc=__import__('hashlib').sha256)
        signature_b64 = _urlsafe_b64encode(signature)
        
        jwt = f"{header_b64}.{payload_b64}.{signature_b64}"
        
        return jwt, vapid_public_key
    except Exception as e:
        logger.error(f"Failed to create VAPID JWT: {e}")
        return None, None


def send_fcm_push_notification(fcm_token, title, body):
    """
    Send push notification using Web Push protocol with VAPID authentication.
    This is compatible with tokens generated by the frontend using VAPID keys.
    """
    if not fcm_token:
        return {'sent': False, 'reason': 'missing_staff_fcm_token'}

    # Try VAPID-based Web Push first
    vapid_public_key = getattr(settings, 'VAPID_PUBLIC_KEY', None)
    vapid_private_key = getattr(settings, 'VAPID_PRIVATE_KEY', None)
    
    if vapid_public_key and vapid_private_key:
        jwt, _ = _create_vapid_jwt()
        if jwt:
            return _send_web_push_vapid(fcm_token, title, body, jwt, vapid_public_key)
    
    # Fallback to legacy FCM server key if available
    firebase_server_key = getattr(settings, 'FIREBASE_SERVER_KEY', None)
    if firebase_server_key:
        return _send_fcm_legacy(fcm_token, title, body, firebase_server_key)
    
    return {'sent': False, 'reason': 'missing_vapid_credentials'}


def _send_web_push_vapid(fcm_token, title, body, jwt, vapid_public_key):
    """Send push notification using Web Push API with VAPID authentication."""
    headers = {
        'Authorization': f'vapid t={jwt}',
        'Content-Encoding': 'aesgcm',
        'TTL': '2419200',  # 4 weeks in seconds
    }
    
    # The body must be encrypted for Web Push
    # For simplicity, we'll send as aesgcm with plaintext (limited browser support)
    # For full production, you'd need to encrypt the payload
    payload = json.dumps({
        'notification': {
            'title': title,
            'body': body,
            'icon': '/icons/icon-192.png',
            'click_action': '/staff/dashboard',
        },
        'data': {
            'url': '/staff/dashboard',
            'appointment': body,
        },
    })
    
    try:
        response = requests.post(
            'https://fcm.googleapis.com/fcm/send',
            headers=headers,
            data=payload,
            params={'registration_token': fcm_token},
            timeout=10
        )
        
        if response.ok:
            return {'sent': True, 'status_code': response.status_code}
        
        body_text = response.text[:500]
        return {
            'sent': False,
            'reason': 'webpush_send_failed',
            'status_code': response.status_code,
            'body': body_text,
        }
    except requests.RequestException as exc:
        return {'sent': False, 'reason': 'webpush_request_exception', 'error': str(exc)[:300]}


def _send_fcm_legacy(fcm_token, title, body, server_key):
    """Send push notification using legacy FCM HTTP API."""
    headers = {
        'Authorization': f'key={server_key}',
        'Content-Type': 'application/json',
    }
    payload = {
        'to': fcm_token,
        'priority': 'high',
        'content_available': True,
        'notification': {
            'title': title,
            'body': body,
        },
        'data': {
            'title': title,
            'body': body,
            'click_action': '/staff/dashboard',
            'url': '/staff/dashboard',
        },
    }

    try:
        response = requests.post('https://fcm.googleapis.com/fcm/send', json=payload, headers=headers, timeout=10)
        if response.ok:
            return {'sent': True, 'status_code': response.status_code}
        body_text = response.text[:500]
        return {
            'sent': False,
            'reason': 'firebase_send_failed',
            'status_code': response.status_code,
            'body': body_text,
            'invalid_token': 'NotRegistered' in body_text or 'InvalidRegistration' in body_text,
        }
    except requests.RequestException as exc:
        return {'sent': False, 'reason': 'firebase_request_exception', 'error': str(exc)[:300]}
