# Generated by Django 4.2.11 on 2026-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_phone_number_to_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
